version: "3.1"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

  # CARD ACCESS TO FABLAB USED CONTAINER:
  # - bitz_access

  bitz_access:
    build: ./bitz_access/
    environment:
      VIRTUAL_HOST: bitz_access.localhost
      VIRTUAL_PORT: 80
    ports:
      - 5000
    expose:
      - 5000
    volumes:
      - ./bitz_access/code

  # FILE SHARING CONTAINERS:
  # - nextcloud_db
  # - nextcloud

  nextcloud_db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD= @dm1n5h@r1ng
      - MYSQL_PASSWORD= @dm1n5h@r1ng
      - MYSQL_DATABASE=sharing
      - MYSQL_USER=admin_sharing

  nextcloud_app:
    image: nextcloud
    environment:
      VIRTUAL_HOST: sharing.localhost
      VIRTUAL_PORT: 80
    expose:
      - 80
    links:
      - nextcloud_db
    volumes:
      - nextcloud:/var/www/html
    restart: always

networks:
  default:
    external:
      name: nginx-proxy

volumes:
  nextcloud:
  db:
